============================= test session starts =============================
platform win32 -- Python 3.7.6, pytest-6.2.2, py-1.10.0, pluggy-0.13.1
rootdir: E:\Python\zdh1
plugins: allure-pytest-2.8.32, forked-1.3.0, html-3.1.1, metadata-1.11.0, ordering-0.6, rerunfailures-9.1.1, xdist-2.2.0
collected 3 items

test_01.py .F.                                                           [100%]

================================== FAILURES ===================================
_____________________________ TestClass.test_two ______________________________

self = <test_01.TestClass object at 0x000002508C6A2A08>

    def test_two(self):
        x = "hello"
>       assert hasattr(x, 'check')
E       AssertionError: assert False
E        +  where False = hasattr('hello', 'check')

test_01.py:21: AssertionError
=========================== short test summary info ===========================
FAILED test_01.py::TestClass::test_two - AssertionError: assert False
========================= 1 failed, 2 passed in 0.06s =========================
